version: '3'
services:
  diskover-web:
    build:
      context: .
      args:
        ES_HOSTS: elasticsearch
    ports:
      - 8080:80
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:5.6.9
    ports:
      - 9200:9200
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    
